name: Build

on: [workflow_dispatch, push, pull_request]

defaults:
  run:
    # Windows では Git for Windows の bash が使用される。
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  test:
    name: Run Build

    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Build Directory
        uses: actions/cache@v3
        with:
          path: |
            Build
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.github_refname }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-${{ env.github_refname }}
            ${{ runner.os }}-${{ runner.arch }}

      - name: Configure
        run: |
          set +e
          cmake -B Build .
          EXIT_CODE=$?
          set -e
          echo "========================================="
          # 復元したキャッシュの状態が期待どおりでなくて Configure に失敗した場合は、
          # ビルドディレクトリを削除して再実行してみる。
          if [[ "${EXIT_CODE}" -eq 0 ]]; then
            rm -rf Build
            cmake -B Build
          fi

      - name: Build
        run: cmake --build Build

