name: Build

on: [workflow_dispatch, push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run Build

    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -B build .

      - name: Build
        run: cmake --build .

